const state={projects:[],selected:null};
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const labels={projects:"受管项目",ready:"状态正常",attention:"需要处理",unmanaged:"尚未接入",unavailable:"路径失效"};
function metric(name,value){return `<article class="metric"><span>${labels[name]}</span><strong>${value}</strong></article>`}
function renderOverview(data){state.projects=data.projects||[];if(!state.selected&&state.projects.length)state.selected=state.projects[0].id;document.querySelector("#metrics").innerHTML=["projects","ready","attention","unmanaged","unavailable"].map(k=>metric(k,data.summary[k]||0)).join("");document.querySelector("#audit").textContent=`本机审计链 ${data.audit.valid?"有效":"异常"} · ${data.audit.events} 条记录`;document.querySelector("#updated").textContent=`更新于 ${new Date(data.generated_at).toLocaleString()}`;renderProjects()}
function renderProjects(){const query=document.querySelector("#search").value.trim().toLowerCase();const rows=state.projects.filter(p=>`${p.label} ${p.path}`.toLowerCase().includes(query));document.querySelector("#projects").innerHTML=rows.length?rows.map(p=>`<button class="project ${esc(p.status)} ${p.id===state.selected?"active":""}" data-id="${esc(p.id)}"><span class="dot"></span><span><strong>${esc(p.label)}</strong><small>${esc(p.path)} · ${esc(p.gate.reason)}</small></span><span class="score">${p.score}%</span></button>`).join(""):`<div class="empty"><p>没有匹配项目</p></div>`;document.querySelectorAll(".project").forEach(button=>button.addEventListener("click",()=>loadProject(button.dataset.id)))}
function control(row){return `<div class="control ${esc(row.status)}"><i></i><div><strong>${esc(row.label)}</strong><span>${esc(row.detail)}</span></div></div>`}
function renderDetail(p){const task=p.task||{},git=p.git||{},policy=p.policy||{};document.querySelector("#detail").innerHTML=`<div class="detail-head"><div><h2>${esc(p.label)}</h2><p>${esc(p.path)}</p></div><span class="badge">${esc(p.status)} · ${p.score}%</span></div><section class="section"><h3>当前治理决策</h3><div class="grid"><div class="fact"><span>Gate</span><strong>${esc(p.gate.decision)}</strong></div><div class="fact"><span>Reason</span><strong>${esc(p.gate.reason)}</strong></div><div class="fact"><span>Task</span><strong>${esc(task.id||"—")}</strong></div><div class="fact"><span>Risk</span><strong>${esc(task.risk||"—")}</strong></div></div></section><section class="section"><h3>仓库状态</h3><div class="grid"><div class="fact"><span>Staged</span><strong>${git.staged??"—"}</strong></div><div class="fact"><span>Unstaged</span><strong>${git.unstaged??"—"}</strong></div><div class="fact"><span>Untracked</span><strong>${git.untracked??"—"}</strong></div><div class="fact"><span>Version</span><strong>${esc(p.version||"未确认")}</strong></div></div></section><section class="section"><h3>治理控制项</h3>${(p.controls||[]).map(control).join("")}</section><section class="section"><h3>策略摘要</h3><p>关键路径 ${policy.critical_paths?.length??0} · 禁止动作 ${policy.deny_actions?.length??0} · 已启用插件 ${(policy.plugins||[]).length}</p></section><section class="section"><h3>验证证据</h3>${(p.evidence||[]).length?p.evidence.map(e=>`<div class="evidence"><span><strong>${esc(e.task||e.file)}</strong><small>${esc(e.ts||"无时间")}</small></span><span>${e.passed?"PASS":"FAIL"}${e.critical?" · critical":""}</span></div>`).join(""):`<p>尚无证据。</p>`}</section>`}
async function loadProject(id){state.selected=id;renderProjects();document.querySelector("#detail").innerHTML='<div class="empty"><p>正在读取项目状态…</p></div>';try{const response=await fetch(`/api/project?id=${encodeURIComponent(id)}`,{cache:"no-store"});if(!response.ok)throw new Error("project request failed");renderDetail(await response.json())}catch(error){document.querySelector("#detail").innerHTML=`<div class="error">${esc(error.message)}</div>`}}
async function refresh(){const button=document.querySelector("#refresh");button.disabled=true;try{const response=await fetch("/api/overview",{cache:"no-store"});if(!response.ok)throw new Error("overview request failed");renderOverview(await response.json());if(state.selected)await loadProject(state.selected)}catch(error){document.querySelector("#projects").innerHTML=`<div class="error">${esc(error.message)}</div>`}finally{button.disabled=false}}
document.querySelector("#refresh").addEventListener("click",refresh);document.querySelector("#search").addEventListener("input",renderProjects);refresh();setInterval(refresh,30000);
